title: Network Foundations
title_separator: "|"
email: gmarti6@uw.edu
description: The Network Foundation team's PTW330 portfolio project
baseurl: "" # the subpath of your site, e.g. /blog
lang: en
local: en-US
name: Greg Martinez
breadcrumbs: true

# Build settings
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-octicons
  - jekyll-include-cache
  - jekyll-paginate

include: ["_pages"]
permalink: /:categories/:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ruby-version
  - scripts/


authors:
  gregmartinez:
    name : Greg Martinez
    email: greg.martinez44@gmail.com
    bio: Data and cloud engineer with a passion for good documentation.
    location: Seattle, WA
    avatar: /assets/bio-avatar.png
    links:
      - label: GitHub
        icon: "fab fa-fw fa-github"
        url: "https://github.com/greg-martinez44"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
